version: '3.8'

networks:
  DS:

services:
  redis:
    image: redis:7.0.11-alpine
    container_name: ds-redis
    networks:
      - DS


  coreapis:
    container_name: ds-coreAPIs
    build: 
      context: ./core
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/usr/src/app/ds-project/ds-core/
    ports:
      - 8010:8000
    environment:
      - DEBUG=true
    depends_on:
      - redis
    networks:
      - DS

  celery:
    container_name: ds-celery
    build: 
      context: ./core
    command: celery --app=coreCelery worker -l INFO
    volumes:
      - ./core:/usr/src/app/ds-project/ds-core/
    environment:
      - DEBUG=true
    depends_on:
      - redis
    networks:
      - DS
    