version: '3.8'

networks:
  DS:

services:
  redis:
    image: redis:7.0.11-alpine
    container_name: ds-redis
    networks:
      - DS

  postgres:
    build:
      context: ./core
      dockerfile: Dockerfile.postgis
    container_name: ds-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: DS
    ports:
      - "5435:5432"  # Map PostgreSQL port to host
    networks:
      - DS
    command: ["postgres", "-c", "log_statement=all"]  # Optional: Enable statement logging

  coreapis:
    container_name: ds-coreAPIs
    build: 
      context: ./core
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./core:/usr/src/app/ds-project/ds-core/
    ports:
      - 8001:8000
    environment:
      - DEBUG=true
    depends_on:
      - redis
      - postgres  # Add PostgreSQL as a dependency
    networks:
      - DS

  celery:
    container_name: ds-celery
    build: 
      context: ./core
    command: celery --app=core worker -l INFO
    volumes:  
      - ./core:/usr/src/app/ds-project/ds-core/
    environment:
      - DEBUG=true
    depends_on:
      - redis
      - postgres  # Add PostgreSQL as a dependency
    networks:
      - DS
    